services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
    sio_db:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-sio_db}
            # !!! Temporary password
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!PasSwoRd!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        ports:
            - "5454:5432"
        volumes:
            - db_data:/var/lib/postgresql/data:rw

volumes:
    db_data: